version: '3'
services:
  node:
    build: .
    # https://qiita.com/s_i_engineer/items/9299e64062d5ba059d40
    # CLI上での対話形式を可能にするために以下の設定が必要である
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
